# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(30, 10, 71, 31))
        self.button_power.setObjectName("button_power")
        self.slider_volume = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_volume.setGeometry(QtCore.QRect(320, 250, 22, 160))
        self.slider_volume.setTracking(False)
        self.slider_volume.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_volume.setObjectName("slider_volume")
        self.slider_minvol = QtWidgets.QLabel(parent=self.centralwidget)
        self.slider_minvol.setGeometry(QtCore.QRect(350, 390, 21, 20))
        self.slider_minvol.setObjectName("slider_minvol")
        self.slider_maxvol = QtWidgets.QLabel(parent=self.centralwidget)
        self.slider_maxvol.setGeometry(QtCore.QRect(350, 250, 21, 20))
        self.slider_maxvol.setObjectName("slider_maxvol")
        self.button_chandown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_chandown.setGeometry(QtCore.QRect(60, 330, 101, 41))
        self.button_chandown.setObjectName("button_chandown")
        self.button_chanup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_chanup.setGeometry(QtCore.QRect(60, 280, 101, 41))
        self.button_chanup.setObjectName("button_chanup")
        self.button_voldown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_voldown.setGeometry(QtCore.QRect(200, 330, 101, 41))
        self.button_voldown.setObjectName("button_voldown")
        self.button_volup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_volup.setGeometry(QtCore.QRect(200, 280, 101, 41))
        self.button_volup.setObjectName("button_volup")
        self.button_mute = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_mute.setGeometry(QtCore.QRect(210, 370, 81, 31))
        self.button_mute.setObjectName("button_mute")
        self.label_channel = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_channel.setGeometry(QtCore.QRect(280, 30, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_channel.setFont(font)
        self.label_channel.setText("")
        self.label_channel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_channel.setObjectName("label_channel")
        self.view_channel = QtWidgets.QLabel(parent=self.centralwidget)
        self.view_channel.setGeometry(QtCore.QRect(50, 40, 300, 200))
        self.view_channel.setMinimumSize(QtCore.QSize(300, 200))
        self.view_channel.setMaximumSize(QtCore.QSize(300, 200))
        self.view_channel.setText("")
        self.view_channel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.view_channel.setObjectName("view_channel")
        self.label_power = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_power.setGeometry(QtCore.QRect(50, 40, 300, 200))
        self.label_power.setMinimumSize(QtCore.QSize(300, 200))
        self.label_power.setMaximumSize(QtCore.QSize(300, 200))
        self.label_power.setText("")
        self.label_power.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_power.setObjectName("label_power")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TvRemote"))
        self.button_power.setText(_translate("MainWindow", "Power"))
        self.slider_minvol.setText(_translate("MainWindow", "0"))
        self.slider_maxvol.setText(_translate("MainWindow", "25"))
        self.button_chandown.setText(_translate("MainWindow", "Ch -"))
        self.button_chanup.setText(_translate("MainWindow", "Ch +"))
        self.button_voldown.setText(_translate("MainWindow", "Vol -"))
        self.button_volup.setText(_translate("MainWindow", "Vol +"))
        self.button_mute.setText(_translate("MainWindow", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
